### ISSUE TITLE
OpenGL 2.1 version ?

### ISSUE THREAD

**Issue by wolfviking0** [halcy/simpleflow#1]
Hi, I am trying to rebuild you sample on OSX, but I have some trouble for create a glut window compatible on GL 4.2.

I want try to convert your demo into WebGL/WebCL do you think it's possible down your OpenGL minimum requirement to OpenGL 2 (WebGL support equivalent OpenGLES2.0). 

I know the demo it's heavy, but I am curious and that can improve my OpenCL to WebCL translator.

Tony

**Comment by halcy** [comment]
I wonder what the minimum version required is. I can play around a little later today and see, I'll get back to you then. Going below 4.0 may require some code changes, but I am guessing it's possible.

I'd actually be really interested in this, as converting to WebCL was something I was looking to doing when it became available enough!

**Comment by wolfviking0** [comment]
I already convert a lot of sample from OpenGL//OpenCL to WebGL/WebCL : http://wolfviking0.github.io/webcl-translator/ for the moment it's work only with webkit-webcl, but i hope soon with firefox extension, and for windows there also chromium from AMD but I don't try it

**Comment by wolfviking0** [comment]
@halcy, you other repository (https://github.com/halcy/openclpt) could be nice to port in OpenGL2 too. I already have some OpenCL path tracer (smallptgpu) but you code struct are the same between both repository, but less shader than WaterSim.
