### ISSUE TITLE
Unhandled exception thrown when trying to run in Windows 7

### ISSUE THREAD

**Issue by liordino** [halcy/simpleflow#2]
Hi,

I succesfully compiled your code on Windows 7, but when I try to run the executable it gives me the following error:

Unhandled exception at 0x77b6dcbb in WaterSim2.exe: 0xC0000374:  A heap has been corrupted.

This occurs on line 31 of the file clgl.pp:

> cl_platform_id\* platform_ids = new cl_platform_id[platform_count];

Any ideas on the cause of this?

Thanks!

**Comment by halcy** [comment]
Hi, 

I believe that might be an OpenCL problem - have you tried compiling and/or running any opencl examples? Maybe a GPU driver update could help fix things.

Alternately, some library used may be broken somehow.

My system is windows 7 as well, it should definitely be possible to run it there.

Good luck,
L. Diener / halcy

**Comment by liordino** [comment]
Thanks!

I'll take a look at it and let you know how it turned out.

**Comment by liordino** [comment]
Don't know exactly where the problem is, but it turned out that if the application continues to execute it works.
