### ISSUE TITLE
Some errors in Screen Space Fluid Rendering with Curvature Flow implementation

### ISSUE THREAD

**Issue by hustruan** [halcy/simpleflow#3]
in particledepth.frag,  
           your particle depth output is clipspacePos.z,  clipspacePos.z is not viewspacePos.z. in OpenGL  
           viewspacePos.z = -clipspacePos. w

in liquidshade.frag  
       eyespace position calculation is not correct

```
  vec3 eyespacePos(vec2 pos) {
         float depth = texture(particleTexture, pos);
         pos = (pos - vec2(0.5f)) * 2.0f;

             // bugs
         return(depth * vec3(-pos.x * projection[0][0], -pos.y * projection[1][1], 1.0f));

             return (depth *vec3(-pos.x / projection[0][0], -pos.y / projection[1][1], 1.0f));
  }
```

**Comment by soulslicer** [comment]
did you fix this

**Comment by halcy** [comment]
I'll be honest here, I have not and it is unlikely I ever will, this was a university student project and I don't really care much to maintain or polish it.
