### ISSUE TITLE
some error in the shaders

### ISSUE THREAD

**Issue by layshua** [halcy/simpleflow#4]
in the simple.frag
"float heightmap(vec2 coords) {
	return texture(terrainTexture, coords); //vec4 <--=/=-->float
}"
should be 
"float heightmap(vec2 coords) {
	return texture(terrainTexture, coords).x;
}"

and also in curvatureflow.frag and liquidshade.fra

**Comment by halcy** [comment]
going to fix that, actually, and some other stuff too

weird that it worked before, guess previous versions of the driver were very forgiving
